import test from 'node:test';
import assert from 'node:assert/strict';
import { MarkerManager } from '../js/map/marker-manager.js';

class ClassList { constructor(owner) { this.owner = owner; } values() { return new Set(this.owner.className.split(/\s+/).filter(Boolean)); } toggle(name, force) { const values = this.values(), enabled = force ?? !values.has(name); enabled ? values.add(name) : values.delete(name); this.owner.className = [...values].join(' '); return enabled; } contains(name) { return this.values().has(name); } }
class Element { constructor(tag) { this.tagName = tag; this.className = ''; this.children = []; this.attributes = {}; this.classList = new ClassList(this); this.textContent = ''; } append(...children) { this.children.push(...children); } setAttribute(name, value) { this.attributes[name] = String(value); } addEventListener() {} }
class Popup { setDOMContent(content) { this.content = content; return this; } isOpen() { return false; } remove() {} }
class Marker { constructor(options) { this.element = options.element; } setLngLat(value) { this.lngLat = value; return this; } addTo(map) { this.map = map; return this; } setPopup(popup) { this.popup = popup; return this; } getPopup() { return this.popup; } remove() { this.removed = true; } }
globalThis.document = { createElement: tag => new Element(tag), createElementNS: (_namespace, tag) => new Element(tag), createTextNode: value => ({ textContent: value }) };
globalThis.maplibregl = { Marker, Popup };
const customer = (id, name) => ({ id, name, latitude: 32.3, longitude: 35.0, hasOrder: true, source: 'demo', createdAt: '2026-01-01T00:00:00.000Z' });
const manager = () => new MarkerManager({}, { isSelected: () => false, toggle() {}, edit() {}, delete() {} });

test('keeps an Arabic customer name before, during and after routing', () => { const markers = manager(), item = customer('1', 'سوبر ماركت أحمد'); markers.render([item], null); const record = markers.markers.get('1'), originalMarker = record.marker; assert.equal(record.label.textContent, item.name); assert.equal(record.label.classList.contains('hidden'), false); assert.equal(record.badge.classList.contains('hidden'), true); markers.render([item], null, [0, 1, 0]); assert.equal(record.label.textContent, item.name); assert.equal(record.badge.textContent, '1'); assert.equal(record.badge.classList.contains('hidden'), false); markers.render([item], null); assert.equal(record.badge.classList.contains('hidden'), true); assert.equal(record.label.textContent, item.name); assert.equal(record.marker, originalMarker); });
test('updates a name safely using textContent and preserves RTL', () => { const markers = manager(), item = customer('1', 'طولكرم'); markers.render([item], null); const record = markers.markers.get('1'); markers.render([{ ...item, name: '<img src=x onerror=alert(1)> نابلس' }], null); assert.equal(record.label.textContent, '<img src=x onerror=alert(1)> نابلس'); assert.equal(record.element.dir, 'rtl'); assert.equal(record.element.children.length, 2); });
test('supports the saved label toggle and ten Arabic names', () => { const markers = manager(), names = ['طولكرم','نابلس','رام الله','جنين','قلقيلية','الخليل','القدس','بيت لحم','أريحا','سلفيت'], customers = names.map((name, index) => customer(String(index), name)); markers.render(customers, null, [], null, false); assert.equal(markers.markers.size, 10); for (const item of customers) { const record = markers.markers.get(item.id); assert.equal(record.label.textContent, item.name); assert.equal(record.label.classList.contains('hidden'), true); } markers.setLabelsVisible(true); for (const record of markers.markers.values()) assert.equal(record.label.classList.contains('hidden'), false); });
