import { formatDate } from '../utils/format.js';

const text = (tag, value, className) => { const element = document.createElement(tag); if (className) element.className = className; element.textContent = value; return element; };
const warehouseIcon = () => { const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg'); svg.setAttribute('viewBox', '0 0 24 24'); svg.setAttribute('aria-hidden', 'true'); const path = document.createElementNS(svg.namespaceURI, 'path'); path.setAttribute('d', 'M3 9 12 4l9 5v11H3V9Zm4 3h10M7 16h3m4 0h3'); svg.append(path); return svg; };
export class MarkerManager {
  constructor(map, handlers) { this.map = map; this.handlers = handlers; this.markers = new Map(); }
  #element(label, type, added = false) { const element = document.createElement('button'); element.type = 'button'; element.className = `map-marker ${type}${added ? ' marker-added' : ''}`; element.setAttribute('aria-label', label); const content = document.createElement('span'); content.append(type === 'warehouse' ? warehouseIcon() : document.createTextNode(label)); element.append(content); return element; }
  #popup(customer) { const root = document.createElement('section'); root.className = 'customer-popup'; root.dir = 'rtl'; root.append(text('strong', customer.name), text('span', customer.hasOrder ? 'لديه طلبية' : 'بلا طلبية', `badge ${customer.hasOrder ? 'order' : ''}`), text('p', `${customer.latitude.toFixed(6)}, ${customer.longitude.toFixed(6)}`), text('p', `المصدر: ${customer.source}`), text('p', `سُجّل: ${formatDate(customer.createdAt)}`)); const actions = document.createElement('div'); actions.className = 'popup-actions'; for (const [label, action] of [[this.handlers.isSelected(customer.id) ? 'إلغاء التحديد' : 'تحديد', 'toggle'], ['تعديل', 'edit'], ['حذف', 'delete']]) { const button = text('button', label); button.type = 'button'; button.addEventListener('click', () => this.handlers[action](customer.id)); actions.append(button); } root.append(actions); return root; }
  render(customers, warehouse, routeOrder = [], addedId = null) { this.clear(); const ranks = new Map(routeOrder.map((pointIndex, position) => [pointIndex, position + 1])); customers.forEach((customer, index) => { const rank = ranks.get(index + 1), label = rank ? String(rank) : String(index + 1), type = rank ? 'route' : customer.hasOrder ? 'order' : 'customer', element = this.#element(label, type, customer.id === addedId); const popup = new maplibregl.Popup({ offset: 26, closeButton: true, maxWidth: '300px' }).setDOMContent(this.#popup(customer)); const marker = new maplibregl.Marker({ element, anchor: 'bottom' }).setLngLat([customer.longitude, customer.latitude]).setPopup(popup).addTo(this.map); this.markers.set(customer.id, marker); }); if (warehouse) { const element = this.#element('المستودع', 'warehouse'); this.warehouseMarker = new maplibregl.Marker({ element, anchor: 'bottom' }).setLngLat([warehouse.longitude, warehouse.latitude]).setPopup(new maplibregl.Popup({ offset: 26 }).setDOMContent(text('strong', 'المستودع / نقطة البداية'))).addTo(this.map); } }
  setPending(point) { this.pendingMarker?.remove(); this.pendingMarker = point ? new maplibregl.Marker({ element: this.#element('الموقع المؤقت', 'pending'), anchor: 'bottom', draggable: true }).setLngLat([point.longitude, point.latitude]).addTo(this.map) : null; return this.pendingMarker; }
  clear() { for (const marker of this.markers.values()) marker.remove(); this.markers.clear(); this.warehouseMarker?.remove(); this.warehouseMarker = null; }
}
